version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/auth-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/posts-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/search-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/embedding-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/likes-service"
    schedule:
      interval: "weekly"