include:
  - auth-service/docker-compose.yaml
  - embedding-service/docker-compose.yaml
  - posts-service/docker-compose.yaml

services:
  traefik:
    image: traefik:v3.4
    ports:
      - "7080:80"
      - "17080:8080" # Traefik dashboard
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro