http:
  routers:
    auth-router:
      rule: "PathPrefix(`/auth.v1.AuthService/`)"
      service: auth-service
      entryPoints:
        - web
    posts-router:
      rule: "PathPrefix(`/posts.v1.PostsService/`)"
      service: posts-service
      entryPoints:
        - web
    search-router:
      rule: "PathPrefix(`/search.v1.SearchService/`)"
      service: search-service
      entryPoints:
        - web
    likes-router:
      rule: "PathPrefix(`/likes.v1.LikesService/`)"
      service: likes-service
      entryPoints:
        - web
  services:
    auth-service:
      loadBalancer:
        servers:
          # h2c = HTTP/2 without TLS
          - url: "h2c://auth-service-1:5080"
          - url: "h2c://auth-service-2:5080"
          - url: "h2c://auth-service-3:5080"
    posts-service:
      loadBalancer:
        servers:
          # h2c = HTTP/2 without TLS
          - url: "h2c://posts-service-1:6080"
          - url: "h2c://posts-service-2:6080"
          - url: "h2c://posts-service-3:6080"
    search-service:
      loadBalancer:
        servers:
          # h2c = HTTP/2 without TLS
          - url: "h2c://search-service-1:5080"
          - url: "h2c://search-service-2:5080"
          - url: "h2c://search-service-3:5080"
    likes-service:
      loadBalancer:
        servers:
          # h2c = HTTP/2 without TLS
          - url: "http://likes-service:40051"