x-posts-service-template: &posts-service-template
  env_file:
    - .env
  build: . # use Dockerfile in the root of the repository
  depends_on:
    posts-redis:
      condition: service_healthy
  environment: &posts-service-env
    REDIS_DSN: redis://:posts_redis_pass@posts-redis:6379

    NATS_URL: 'nats:4222'
    POSTS_STREAM_NAME: POSTS

    SCYLLA_HOSTS: 'scylla-node1:9042,scylla-node2:9042,scylla-node3:9042,scylla-node4:9042,scylla-node5:9042'
    SCYLLA_USERNAME: cassandra
    SCYLLA_PASSWORD: cassandra
    SCYLLA_KEYSPACE: posts

    JWKS_PATH: 'http://auth-service-1:5080/auth/.well-known/jwks.json'


include:
  - scylladb-compose-include.yaml

services:
  posts-redis:
    image: redis:7.4.0
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "posts_redis_pass", "ping" ]
      interval: 1s
    ports:
      - '6064:6379'
    command: redis-server --requirepass posts_redis_pass
    volumes:
      - redis_data:/data

  posts-service-1:
    depends_on:
      scylla-node1:
        condition: service_healthy
      scylla-node2:
        condition: service_healthy
      scylla-node3:
        condition: service_healthy
      scylla-node4:
        condition: service_healthy
      scylla-node5:
        condition: service_healthy
    <<: *posts-service-template
    ports:
      - '6070:6080'
      - '6072:6082'
    environment:
      <<: *posts-service-env
      SERVER_ADDRESS: 0.0.0.0:6080
      SERVER_METRICS_ADDRESS: 0.0.0.0:6082
      APPLY_MIGRATIONS: true

  posts-service-2:
    depends_on:
      posts-service-1:
        condition: service_healthy
    <<: *posts-service-template
    ports:
      - '6080:6080'
      - '6082:6082'
    environment:
      <<: *posts-service-env
      SERVER_ADDRESS: 0.0.0.0:6080
      SERVER_METRICS_ADDRESS: 0.0.0.0:6082

  posts-service-3:
    depends_on:
      posts-service-1:
        condition: service_healthy
    <<: *posts-service-template
    ports:
      - '6090:6080'
      - '6092:6082'
    environment:
      <<: *posts-service-env
      SERVER_ADDRESS: 0.0.0.0:6080
      SERVER_METRICS_ADDRESS: 0.0.0.0:6082

volumes:
  pg_data:
  redis_data:
