ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 1

# DISABLED RULES
#[rule.add-constant] -- hard to configure exceptions
#[rule.argument-limit] -- better to be limited by max length
#[rule.package-comments] -- we don't write a public library, so it is not required in our project
#[rule.exported] -- we don't write a public library, so it is not required in our project
#[rule.nested-structs] - we use nested structs
#[rule.max-public-structs] -- why does this rule even exist?

[rule.atomic]
[rule.bare-return]
[rule.blank-imports]
[rule.bool-literal-in-expr]
[rule.call-to-gc]
[rule.confusing-naming]
[rule.confusing-results]
#[rule.cognitive-complexity]
#    arguments =[14]
[rule.constant-logical-expr]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.cyclomatic]
    arguments =[20]
[rule.deep-exit]
[rule.defer]
[rule.dot-imports]
[rule.duplicated-imports]
[rule.early-return]
[rule.empty-block]
[rule.empty-lines]
[rule.error-naming]
[rule.error-return]
[rule.error-strings]
[rule.errorf]
[rule.file-header]
#[rule.flag-parameter]
[rule.function-result-limit]
[rule.get-return]
[rule.identical-branches]
[rule.if-return]
[rule.increment-decrement]
[rule.indent-error-flow]
[rule.imports-blacklist]
[rule.import-shadowing]
#[rule.line-length-limit]
#    arguments =[150]
[rule.modifies-parameter]
[rule.modifies-value-receiver]
[rule.range]
[rule.range-val-in-closure]
[rule.range-val-address]
[rule.receiver-naming]
[rule.redefines-builtin-id]
[rule.string-of-int]
[rule.struct-tag]
[rule.string-format]
[rule.superfluous-else]
[rule.time-naming]
[rule.var-naming]
[rule.var-declaration]
[rule.unconditional-recursion]
[rule.unexported-naming]
[rule.unexported-return]
[rule.unhandled-error]
    arguments = ["fmt.Printf", "fmt.Println"]
[rule.unnecessary-stmt]
[rule.unreachable-code]
[rule.unused-parameter]
[rule.unused-receiver]
[rule.waitgroup-by-value]

[directive.specify-disable-reason]