// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	UserID       uuid.UUID `db:"user_id"`
	Email        string    `db:"email"`
	Username     string    `db:"username"`
	Name         string    `db:"name"`
	Description  string    `db:"description"`
	AvatarUrl    *string   `db:"avatar_url"`
	PasswordHash []byte    `db:"password_hash"`
	IsAdmin      bool      `db:"is_admin"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
}
