// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ClearUserAvatarURL(ctx context.Context, userID uuid.UUID) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteUserByID(ctx context.Context, userID uuid.UUID) error
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, userID uuid.UUID) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetUsersByIDs(ctx context.Context, userIds []uuid.UUID) ([]GetUsersByIDsRow, error)
	UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) error
	UpdateUserPassword(ctx context.Context, passwordHash []byte, userID uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
