version: "3.8"

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--cluster_name NATS -js --http_port 8222 "
    networks: [ "nats" ]

  service:
    build: .
    ports:
      - "8000:8000"     # FastAPI HTTP
      - "50051:50051"   # gRPC
    volumes:
      - ./app:/app
      - ${HOME}/.cache:/root/.cache  # Mount your laptop's model cache (e.g., HF/torch/transformers)
    environment:
      - TRANSFORMERS_CACHE=/root/.cache/huggingface/transformers
      - TORCH_HOME=/root/.cache/torch
    restart: unless-stopped

networks:
  nats:
    name: nats