services:
  nats:
    image: nats:2.11-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--cluster_name NATS -js --http_port 8222 "
    healthcheck:
      test: wget http://localhost:8222/healthz -q -S -O -
      start_period: 3s
      retries: 3
      timeout: 3s
      interval: 14s

  embeddings-service:
    build: .
    ports:
      - "8000:8000"     # FastAPI HTTP
      - "50051:50051"   # gRPC
    volumes:
      - ./app:/app
      - ${HOME}/.cache:/root/.cache  # Mount your laptop's model cache (e.g., HF/torch/transformers)
    environment:
      - HF_HOME=/root/.cache/huggingface/
      - TORCH_HOME=/root/.cache/torch
      - NATS_URL=nats://nats:4222
    restart: unless-stopped