name: Build Auth Service

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths:
      - '.github/workflows/_build.yml'
      - '.github/workflows/build-api-auth.yml'
      - 'auth-service/**'
  pull_request:
    paths:
      - '.github/workflows/_build.yml'
      - '.github/workflows/build-api-auth.yml'
      - 'auth-service/**'

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Service
    uses: ./.github/workflows/_build.yml
    with:
      context: 'auth-service'
      service: 'auth-service'
