name: Build Posts Service

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_build.yml'
      - '.github/workflows/build-api-search.yml'
      - 'search-service/**'
  pull_request:
    paths:
      - '.github/workflows/_build.yml'
      - '.github/workflows/build-api-search.yml'
      - 'search-service/**'
permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Service
    uses: ./.github/workflows/_build.yml
    with:
      context: 'search-service'
      service: 'search-service'
